### ISSUE TITLE
Support Regex

### ISSUE THREAD

**Issue by odin568** [darkphnx/ical-filter-proxy#19]
Hi,
just stumbled over your tool, exactly what I need.
Only thing I would require is having regex support on the summary/description field.
So beside equals and startswith a new option "matches".
I tried setting up Ruby (totally new to Ruby honestly, but seems the tool is not compatible with Ruby 3 - so need to install Ruby 2.5. Will try to come up with a PR and try my best :)

**Comment by darkphnx** [comment]
I've not put in official Ruby 3 support yet as I run it on Lambda, which is stuck on Ruby 2.7.

Regex match would be great. Should be reasonably straightforward to add to filter_rule.rb.
