### ISSUE TITLE
Add versioning and provide artifacts

### ISSUE THREAD

**Issue by odin568** [darkphnx/ical-filter-proxy#27]
Hi @darkphnx ,
thanks for all your support so far!

Some background to my use-case. I want to use your tool for our local fire department. We have a public google calendar with all events. Now our mobile alarm software also has in addition an ical import feature which integrates nicely. Unfortunatly there I want to split things from one "truth" calendar into multiple logical ones (for different groups).

I already run some things on Docker for that purpose (@FFW-Baudenbach) and this would be the next step.
So what I need at the end is a versioned docker container out of your repo. As it runs on a RaspberryPi, it needs to be available for multiple architectures (docker-buildx) like ARMv8, etc. The ruby base image supports that.
I already do such stuff, i.e. with https://github.com/FFW-Baudenbach/FE2_Kartengenerierung for your reference but only with GitHub actions, not with CircleCI.

One possibility is to build it on my own on my fork.
Alternatively if you see a value, why not integrate it into your repo? 
Unfortunately the effort would be more on your side, so feel free to give your thoughts and a 👍 or 👎 

Thanks so far a lot!

**Comment by darkphnx** [comment]
That's a great use case - happy that this project can help.

I haven't build a multi-arch image before, but I'd like to give it a go. It looks to be possible with CircleCI these days, so I'll give that a go first, knowing I can fall back on Github Actions if necessary.

**Comment by darkphnx** [comment]
For versioning, I don't really want to get into running a semantic-version pipeline for this, I don't update it often enough. If you want to pin a particular version, each release is tagged with the current commit sha.

**Comment by odin568** [comment]
That was quick :) 
Can confirm it runs on my RaspberryPi!

**Comment by darkphnx** [comment]
Winding down for Christmas and no-one is bugging me for anything else! Had a bit of spare time on my hands.

Glad to hear it's running correctly. AWS Lambda builds are feeling a little neglected now - I'll have to update them next.

**Comment by odin568** [comment]
Yes, same for me :)
Yeah full semantic versioning might be too much here, agree. Having commit-sha and latest should be fine.
Have a great christmas time!
Thanks for your prompt effort. Got my first hands on Ruby with this :muscle:
